Iban
ing-bank/lion pull request #1163
Opened 2021-01-04 16:56 UTC by sidona

## What I did

1. improve validation for blacklist country - iban

2021-01-04 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ing-bank/lion?pullRequest=1163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ing-bank/lion?pullRequest=1163) before we can accept your contribution.<br/><hr/>**sdonose** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ing-bank/lion?pullRequest=1163) it.</sub>

2021-01-06 10:35 UTC, jorenbroekema requested changes
Seems like a good idea to me, so lowercase IBANs get properly validated, and you can pass `['en']` as well as `['EN']` as a param, and it just gets normalized to uppercase.

However, some things you need to do still:
- [ ] Sign CLA
- [ ] Remove debugger statements
- [ ] Revert removing the .editorconfig file, we still want that 😅 
- [ ] Add a test to confirm normalisation behaviour of the country param
- [ ] Add a test to confirm normalisation behaviour of the modelValue
- [ ] Add a changeset with a patch, run `yarn changeset` `npx changeset` and follow the menu and create a good changelog message for this change. If needed we can also do this for you :)

2021-04-15 11:57 UTC, tlouisse commented
I completed the suggesions from @jorenbroekema 
Thanks for the contribution @sidona!

2021-04-15 11:58 UTC, tlouisse approved these changes

2021-04-15 12:30 UTC, merged