refactor: update input-datepicker package exports
ing-bank/lion pull request #1244
Opened 2021-02-24 17:28 UTC by Knorgias

## What I did

1.

2021-02-24 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ing-bank/lion?pullRequest=1244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ing-bank/lion?pullRequest=1244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ing-bank/lion?pullRequest=1244) it.</sub>

2021-03-01 17:17 UTC, jorenbroekema commented on packages/checkbox-group/define.js
> +customElements.define('lion-checkbox', LionCheckbox);
```suggestion
import '@lion/checkbox-group/define-checkbox-group';
import '@lion/checkbox-group/define-checkbox';
import '@lion/checkbox-group/define-checkbox-indeterminate';
```

so then end user can do

```js
import '@lion/checkbox-group/define';

// or

import '@lion/checkbox-group/define-checkbox-group';
```

2021-03-01 17:22 UTC, jorenbroekema commented on packages/form-integrations/test/form-reset.test.js
> +import '@lion/checkbox-group/define-checkbox-group';
```suggestion
import '@lion/checkbox-group/define';
```

2021-03-01 17:23 UTC, jorenbroekema commented on packages/form-integrations/test/helpers/umbrella-form.js
> +import '@lion/checkbox-group/define-checkbox';
```suggestion
import '@lion/checkbox-group/define';
```

2021-03-01 17:25 UTC, jorenbroekema requested changes

2021-03-01 17:25 UTC, jorenbroekema commented on packages/form-integrations/test/model-value-consistency.test.js
> +import '@lion/checkbox-group/define-checkbox';
```suggestion
import '@lion/checkbox-group/define';
```

2021-03-02 11:16 UTC, daKmoR commented on packages/calendar/test-helpers/index.js
> +export * from './CalendarObject.js';
please define every export (e.g. no star exports) for better support of bundlers

2021-03-04 15:55 UTC, jorenbroekema commented on packages/combobox/docs/listboxData.js
> +export const listboxData = [
Copy from packages/listbox. We were importing it from listbox before but we don't have an export maps entry for it so WDS could not resolve it. Imo, just copying is fine for this...

2021-03-04 15:56 UTC, jorenbroekema commented on .storybook/main.js
> +    ])
With globby like this we can at least use JS to filter out stuff that the glob caught that we don't want, makes it a bit easier than puzzling for multiple days on a glob pattern that works 😓

2021-03-04 16:32 UTC, jorenbroekema approved these changes

2021-03-04 16:33 UTC, jorenbroekema commented
If we can accept that our storybook code snippets are gone I suppose we could merge, but not having copy-able things in our demos is a shame 😓

2021-03-11 07:43 UTC, daKmoR commented
has been incorporated into the `chore/staticDocs` branch

2021-03-11 07:43 UTC, closed without merging