Chore/add private protected types
ing-bank/lion pull request #1263
Opened 2021-03-15 17:36 UTC by Knorgias

## What I did

1. Added @protected & @private to _ & __ properties and methods

2021-03-16 07:22 UTC, jorenbroekema requested changes

2021-03-16 07:22 UTC, jorenbroekema commented on packages/calendar/src/LionCalendar.js
> +       * @private
I don't believe TS looks at static get properties for class fields, so these @private type annotations probably need to be moved to where the class field is initialised (usually in the constructor).

2021-03-16 07:22 UTC, jorenbroekema commented on packages/combobox/src/LionCombobox.js
> +     * @protected
private right?

2021-03-16 07:22 UTC, jorenbroekema commented on packages/combobox/src/LionCombobox.js
> +     * @protected
private

2021-03-16 07:22 UTC, jorenbroekema commented on packages/combobox/src/LionCombobox.js
> +   * @private
protected

2021-03-16 07:22 UTC, jorenbroekema commented on packages/form-core/src/registration/FormRegistrarMixin.js
> +         * @protected
static get prop so this @protected won't do much, annotate in initialisation instead.

2021-03-16 07:22 UTC, jorenbroekema commented on packages/form-core/src/validate/ValidateMixin.js
> +         * @protected
static get prop, see above comment

2021-03-17 13:54 UTC, jorenbroekema commented
Reviewed all commits since my previous review. Looks good 👍 

Now we just need to:
- Rebase on latest master --> fix merge conflict
- Add a changeset (patch) for all changed packages
- Squash all commits into one

Then we can merge :)

2021-03-31 09:06 UTC, tlouisse commented on packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
> +    if (elIndeterminate) {
I think the test should fail if `elIndeterminate` is null (is it possible to remove this if? (according to lin 154, TS shouldn't complain)

2021-03-31 09:08 UTC, tlouisse commented on packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
> +    if (elFirstIndeterminate) {
see comments above

2021-03-31 09:08 UTC, tlouisse commented on packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
> +    if (elSecondIndeterminate) {
see comments above

2021-03-31 09:12 UTC, tlouisse commented on packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
> +    const ElNestedSubCheckboxes = getProtectedMembers(elNestedIndeterminate);
Instance or 'regular variable' names should not be capitalized. So usually we have the convention:

```js
class MyClass {}

const myClass = new MyClass();

```

So in the example above `MyClass` is the constructor, `myClass` is the instance. As a rule of thumb, we can say that only constructor names should be capitalized, all other variable names should start with a lowercase char.

2021-03-31 09:14 UTC, tlouisse commented on packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
> +    if (elNestedIndeterminate) ElNestedSubCheckboxes.subCheckboxes[0]._inputNode.click();
We have the convention to always use parentheses and newlines for an if for readability (should be captured by linting though...)

2021-04-01 13:40 UTC, tlouisse commented
Hi, great start 💪 

If we look at [this](https://github.com/ing-bank/lion/issues/1140) issue, not everything is tackled. (we focused mainly on point 2 now, I think.)
Next step would be to also add all the info to the mixin type declarations and add all the descriptions there as well (especially for public methods and protected methods)

2021-04-01 16:01 UTC, tlouisse approved these changes

2021-04-01 17:49 UTC, merged