Add legacy branch for release
ing-bank/lion pull request #1410
Opened 2021-06-02 13:22 UTC by Knorgias

Set up github actions workflows to also trigger on PR/merge to legacy branch

## What I did

1. Added new "legacy" branch in workflow for releasing legacy patch updates

2021-06-02 13:26 UTC, Knorgias commented
I cannot access the “Settings” of ing-bank/lion in order to protect branch "legacy" with the same protection rules as master.
I guess I'll either have to be granted permissions or one of the repository owners can do this instead.

2021-06-02 14:16 UTC, gerjanvangeest approved these changes

2021-06-07 07:44 UTC, jorenbroekema requested changes

2021-06-07 07:44 UTC, jorenbroekema commented on .github/workflows/release.yml
>        - master
What if we remove master here, and just merge this branch to legacy instead of to master?

2021-06-07 07:44 UTC, jorenbroekema commented
I'll fix the settings when this is merged :)

2021-06-07 10:16 UTC, jorenbroekema commented
Sorry for all the formatting changes, is a result of https://github.com/prettier/prettier/blob/main/CHANGELOG.md#231  Preserve attributes order for element node + Fix incorrectly wrapped arrow functions with return types change

2021-06-09 08:15 UTC, closed without merging