chore: wrote a blogpost on @lion/ui
ing-bank/lion pull request #1946
Opened 2023-03-20 14:49 UTC by DannyMoerkerke

## What I did

1. wrote a blogpost on @lion/ui

It has no image yet.

2023-03-22 09:39 UTC, gerjanvangeest commented on docs/blog/introducing-lion-ui.md
> +`@lion/ui` has a new single CHANGELOG.md in `/packages/ui` for the whole package. The older individual changelogs can be
```suggestion
`@lion/ui` has [a new single CHANGELOG.md]( https://github.com/ing-bank/lion/blob/master/packages/ui/CHANGELOG.md) in `/packages/ui` for the whole package. The older individual changelogs can be
```

2023-04-04 11:37 UTC, tkgroot requested changes
I agree with gerjanvangeest's suggested change.

2023-04-05 07:15 UTC, tkgroot approved these changes

2023-04-05 07:39 UTC, gerjanvangeest approved these changes

2023-04-05 07:39 UTC, merged