Feat/workflow improvement
ing-bank/lion pull request #1989
Opened 2023-05-26 17:38 UTC by Farzannajipour

## What I did

1. Updated the versions of actions/setup-node and actions/checkout in the release.yml file. 
2. Updated the `verify.yml` file to include the setup-common-steps job. The setup-common-steps job is responsible for setting up the common steps required for the verify workflow. By adding this job, we ensure that the necessary setup is performed before running the verify job.

The update includes the following changes:

Added the setup-common-steps job to the jobs section.
Added the needs keyword to the verify, browser-tests, node-tests, and node-tests-windows jobs, specifying that they depend on the setup-common-steps job.

2023-05-26 17:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ing-bank/lion?pullRequest=1989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ing-bank/lion?pullRequest=1989) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ing-bank/lion?pullRequest=1989) it.</sub>

2023-06-01 11:07 UTC, gerjanvangeest requested changes
Hi @Farzannajipour,

Thanks for updating these outdated files. But why not go with the latest [actions/checkout](https://github.com/actions/checkout/blob/main/package.json) and [action/setup-node](https://github.com/actions/setup-node/blob/main/package.json) (v3)?

2023-06-01 11:07 UTC, gerjanvangeest commented on .github/workflows/verify.yml
> +  setup-common-steps:
```suggestion
  init:
```

2023-06-05 06:56 UTC, gerjanvangeest approved these changes

2023-06-05 07:15 UTC, tkgroot approved these changes

2023-06-05 07:16 UTC, tlouisse approved these changes

2023-06-05 07:17 UTC, merged