Fix/overlay growing margin, issue 2323
ing-bank/lion pull request #2331
Opened 2024-08-12 10:21 UTC by ka9de

## What I did

1. fix the _keepBodySize to return instantly if controller uses local placement
2. wrote a test to confirm this

2024-08-12 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ing-bank/lion?pullRequest=2331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ing-bank/lion?pullRequest=2331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ing-bank/lion?pullRequest=2331) it.</sub>

2024-08-26 07:32 UTC, tlouisse commented on .changeset/avoid-growing-margin.md
> +fix(2323): avoid growing margin when using overlays with tooltips
```suggestion
fix: [overlays] avoid growing margin when using overlays with tooltips
```

2024-08-26 07:32 UTC, tlouisse commented on packages/ui/components/overlays/src/OverlayController.js
> +    if (this.placementMode !== 'global') {
```suggestion
    if (!this.preventsScroll) {
```

2024-08-26 07:35 UTC, tlouisse commented on packages/ui/components/overlays/test/OverlayController.test.js
> +      ...withLocalTestConfig(),
```suggestion
      ...withLocalTestConfig(),
      preventsScroll: true,
```

2024-08-26 07:39 UTC, tlouisse commented on packages/ui/components/overlays/test/OverlayController.test.js
> +    });
Looks great, maybe you can also test here for the `preventsScroll: true` case...

```
      overlayControllerLocal.updateConfig({ preventsScroll: true }); 

      expect(overlayControllerLocal.__bodyMarginRightInline).to.not.equal(undefined);
      expect(overlayControllerLocal.__bodyMarginRight).to.not.equal(undefined);

```

2024-08-26 07:43 UTC, tlouisse requested changes
Thanks for the PR!

The changelog was correct indeed 👍 

Can you look at the suggestions? It would also be nice if you could squash all commits into one (but we can also do it while merging...)

When these latest changes are implemented, we will merge it 💪

2024-08-26 07:44 UTC, tlouisse commented
closes https://github.com/ing-bank/lion/issues/2323

2024-08-28 10:05 UTC, tlouisse commented on packages/ui/components/overlays/test/OverlayController.test.js
> +      expect(overlayControllerLocal.__bodyMarginRight).to.equal(undefined);
```suggestion
      expect(overlayControllerLocal.__bodyMarginRight).to.equal(undefined);
      
      overlayControllerLocal.updateConfig({ preventsScroll: true }); 
      expect(overlayControllerLocal.__bodyMarginRightInline).to.not.equal(undefined);
      expect(overlayControllerLocal.__bodyMarginRight).to.not.equal(undefined);
```

2024-08-28 10:48 UTC, ka9de reviewed
I fixed some linting problem and updated the tests with some text

2024-08-28 11:55 UTC, tlouisse approved these changes

2024-08-28 11:57 UTC, tlouisse commented
Thanks for the PR!

2024-08-28 11:59 UTC, merged